#!/bin/sh
set -eu

TEMPLATE_DIR="/etc/nginx/templates"
OUTPUT_FILE="/etc/nginx/conf.d/default.conf"
ENVIRONMENT="${ENVIRONMENT:-development}"
TARGET_SERVICE_HOST="${TARGET_SERVICE_HOST:-hello-world}"
TARGET_SERVICE_PORT="${TARGET_SERVICE_PORT:-3000}"
NGINX_SERVER_NAME="${NGINX_SERVER_NAME:-localhost}"
NGINX_DNS_RESOLVERS="${NGINX_DNS_RESOLVERS:-8.8.8.8 8.8.4.4}"
NGINX_DNS_RESOLVER_TIMEOUT="${NGINX_DNS_RESOLVER_TIMEOUT:-5s}"
NGINX_DNS_RESOLVER_VALID="${NGINX_DNS_RESOLVER_VALID:-300s}"
NGINX_SSL_PROTOCOLS="${NGINX_SSL_PROTOCOLS:-TLSv1.2 TLSv1.3}"
NGINX_SSL_CIPHERS="${NGINX_SSL_CIPHERS:-ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384}"
NGINX_SSL_SESSION_TIMEOUT="${NGINX_SSL_SESSION_TIMEOUT:-1d}"
NGINX_SSL_SESSION_CACHE="${NGINX_SSL_SESSION_CACHE:-shared:SSL:10m}"

TEMPLATE_FILE="${TEMPLATE_DIR}/${ENVIRONMENT}.conf.template"

if [ ! -f "$TEMPLATE_FILE" ]; then
  echo "Nginx template not found: ${TEMPLATE_FILE}" >&2
  ls "$TEMPLATE_DIR"
  exit 1
fi

export TARGET_SERVICE_HOST TARGET_SERVICE_PORT NGINX_SERVER_NAME \
  NGINX_DNS_RESOLVERS NGINX_DNS_RESOLVER_TIMEOUT NGINX_DNS_RESOLVER_VALID \
  NGINX_SSL_PROTOCOLS NGINX_SSL_CIPHERS NGINX_SSL_SESSION_TIMEOUT NGINX_SSL_SESSION_CACHE

envsubst '$TARGET_SERVICE_HOST $TARGET_SERVICE_PORT $NGINX_SERVER_NAME $NGINX_DNS_RESOLVERS $NGINX_DNS_RESOLVER_TIMEOUT $NGINX_DNS_RESOLVER_VALID $NGINX_SSL_PROTOCOLS $NGINX_SSL_CIPHERS $NGINX_SSL_SESSION_TIMEOUT $NGINX_SSL_SESSION_CACHE' < "$TEMPLATE_FILE" > "$OUTPUT_FILE"

echo "Generated nginx config for ${ENVIRONMENT} at ${OUTPUT_FILE}"
